### ISSUE TITLE
Console.log the ENV vars

### ISSUE THREAD

**Issue by willrstern** [ericclemmons/per-env#2]
Not necessary, but would be nice to console.log which vars were set when running the script.

**Comment by ericclemmons** [comment]
This ended up being a decent chunk of noise for me when testing (which was a nice benefit of doing it this way vs. having them hard-coded in the scripts).

What's the problem you're running into?  The variables not being set?

You can do something like:

```js
    "start": "per-env",
    "prestart:development": "printenv",
    "start:development": "node src/server",
```

Does that work?

**Comment by willrstern** [comment]
no, no issue with variables, just thought it'd be cool to see them in the console, but not a requirement, more of a thought.

**Comment by ericclemmons** [comment]
I think I'm still misunderstanding.  Re-open or post back with what you were looking for (or does `printenv` handle it?) and we can go from there.

No problem with a `--verbose` or `--debug` flag, but I don't think I ran into the use-case outside of the initial project creation...
